/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\calculator_export.glb -t -s 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane: THREE.Mesh
    Plane_1: THREE.Mesh
    Plane_2: THREE.Mesh
    Plane002: THREE.Mesh
    Plane002_1: THREE.Mesh
    Plane005: THREE.Mesh
    Plane005_1: THREE.Mesh
    Plane006: THREE.Mesh
    Plane006_1: THREE.Mesh
    Plane007: THREE.Mesh
    Plane007_1: THREE.Mesh
    Text004: THREE.Mesh
    Text004_1: THREE.Mesh
    Plane009: THREE.Mesh
    Plane009_1: THREE.Mesh
    Plane010: THREE.Mesh
    Plane010_1: THREE.Mesh
    Plane012: THREE.Mesh
    Plane012_1: THREE.Mesh
    Plane013: THREE.Mesh
    Plane013_1: THREE.Mesh
    Plane014: THREE.Mesh
    Plane014_1: THREE.Mesh
    Plane016: THREE.Mesh
    Plane016_1: THREE.Mesh
    Plane004: THREE.Mesh
    Plane004_1: THREE.Mesh
    Plane001: THREE.Mesh
    Plane001_1: THREE.Mesh
    Plane017: THREE.Mesh
    Plane017_1: THREE.Mesh
    Plane019: THREE.Mesh
    Plane019_1: THREE.Mesh
    Plane003: THREE.Mesh
    Plane003_1: THREE.Mesh
    Plane015: THREE.Mesh
    Plane015_1: THREE.Mesh
    Plane018: THREE.Mesh
    Plane018_1: THREE.Mesh
    Plane011: THREE.Mesh
    Plane011_1: THREE.Mesh
  }
  materials: {
    white: THREE.MeshStandardMaterial
    display: THREE.MeshStandardMaterial
    black: THREE.MeshStandardMaterial
    ['black.001']: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function CalculatorModel(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/calculator_export.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Plane.geometry} material={materials.white} />
      <mesh castShadow receiveShadow geometry={nodes.Plane_1.geometry} material={materials.display} />
      <mesh castShadow receiveShadow geometry={nodes.Plane_2.geometry} material={materials.black} />
      <mesh castShadow receiveShadow geometry={nodes.Plane002.geometry} material={materials.white} />
      <mesh castShadow receiveShadow geometry={nodes.Plane002_1.geometry} material={materials.black} />
      <mesh castShadow receiveShadow geometry={nodes.Plane005.geometry} material={materials.white} />
      <mesh castShadow receiveShadow geometry={nodes.Plane005_1.geometry} material={materials.black} />
      <mesh castShadow receiveShadow geometry={nodes.Plane006.geometry} material={materials.white} />
      <mesh castShadow receiveShadow geometry={nodes.Plane006_1.geometry} material={materials.black} />
      <mesh castShadow receiveShadow geometry={nodes.Plane007.geometry} material={materials.white} />
      <mesh castShadow receiveShadow geometry={nodes.Plane007_1.geometry} material={materials.black} />
      <mesh castShadow receiveShadow geometry={nodes.Text004.geometry} material={materials.black} />
      <mesh castShadow receiveShadow geometry={nodes.Text004_1.geometry} material={materials.white} />
      <mesh castShadow receiveShadow geometry={nodes.Plane009.geometry} material={materials.white} />
      <mesh castShadow receiveShadow geometry={nodes.Plane009_1.geometry} material={materials.black} />
      <mesh castShadow receiveShadow geometry={nodes.Plane010.geometry} material={materials.white} />
      <mesh castShadow receiveShadow geometry={nodes.Plane010_1.geometry} material={materials.black} />
      <mesh castShadow receiveShadow geometry={nodes.Plane012.geometry} material={materials.white} />
      <mesh castShadow receiveShadow geometry={nodes.Plane012_1.geometry} material={materials.black} />
      <mesh castShadow receiveShadow geometry={nodes.Plane013.geometry} material={materials.white} />
      <mesh castShadow receiveShadow geometry={nodes.Plane013_1.geometry} material={materials.black} />
      <mesh castShadow receiveShadow geometry={nodes.Plane014.geometry} material={materials.white} />
      <mesh castShadow receiveShadow geometry={nodes.Plane014_1.geometry} material={materials.black} />
      <mesh castShadow receiveShadow geometry={nodes.Plane016.geometry} material={materials.white} />
      <mesh castShadow receiveShadow geometry={nodes.Plane016_1.geometry} material={materials.black} />
      <mesh castShadow receiveShadow geometry={nodes.Plane004.geometry} material={materials['black.001']} />
      <mesh castShadow receiveShadow geometry={nodes.Plane004_1.geometry} material={materials.black} />
      <mesh castShadow receiveShadow geometry={nodes.Plane001.geometry} material={materials.white} />
      <mesh castShadow receiveShadow geometry={nodes.Plane001_1.geometry} material={materials.black} />
      <mesh castShadow receiveShadow geometry={nodes.Plane017.geometry} material={materials.white} />
      <mesh castShadow receiveShadow geometry={nodes.Plane017_1.geometry} material={materials.black} />
      <mesh castShadow receiveShadow geometry={nodes.Plane019.geometry} material={materials.white} />
      <mesh castShadow receiveShadow geometry={nodes.Plane019_1.geometry} material={materials.black} />
      <mesh castShadow receiveShadow geometry={nodes.Plane003.geometry} material={materials.white} />
      <mesh castShadow receiveShadow geometry={nodes.Plane003_1.geometry} material={materials.black} />
      <mesh castShadow receiveShadow geometry={nodes.Plane015.geometry} material={materials.white} />
      <mesh castShadow receiveShadow geometry={nodes.Plane015_1.geometry} material={materials.black} />
      <mesh castShadow receiveShadow geometry={nodes.Plane018.geometry} material={materials.white} />
      <mesh castShadow receiveShadow geometry={nodes.Plane018_1.geometry} material={materials.black} />
      <mesh castShadow receiveShadow geometry={nodes.Plane011.geometry} material={materials.white} />
      <mesh castShadow receiveShadow geometry={nodes.Plane011_1.geometry} material={materials.black} />
    </group>
  )
}

useGLTF.preload('/calculator_export.glb')
